# Generated by Django 5.2.4 on 2025-12-10 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+37529XXXXXXX'.", regex='^\\+37529\\d{7}')], verbose_name='Телефон'),
        ),
    ]
