# Generated by Django 5.2 on 2025-06-05 09:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование штрафа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма штрафа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип штрафа',
                'verbose_name_plural': 'Типы штрафов',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='Действует с')),
                ('valid_to', models.DateField(verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='Максимальное количество использований')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Текущее количество использований')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Активен'), ('returned', 'Возвращен'), ('cancelled', 'Отменен'), ('overdue', 'Просрочен')], default='pending', max_length=20, verbose_name='Статус')),
                ('rental_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выдачи')),
                ('rental_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество дней')),
                ('expected_return_date', models.DateField(verbose_name='Ожидаемая дата возврата')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата возврата')),
                ('rental_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма проката')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма скидки')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Примечания о состоянии автомобиля')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to='rentals.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='vehicles.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Прокат',
                'verbose_name_plural': 'Прокаты',
                'ordering': ['-rental_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField(default=django.utils.timezone.now, verbose_name='Дата применения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('penalty_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_penalties', to='rentals.penaltytype', verbose_name='Тип штрафа')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='rentals.rental', verbose_name='Прокат')),
            ],
            options={
                'verbose_name': 'Штраф по прокату',
                'verbose_name_plural': 'Штрафы по прокатам',
            },
        ),
    ]
