# Generated by Django 5.2.4 on 2025-09-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='company/certificates/', verbose_name='Сертификат'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='История компании'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео о компании'),
        ),
    ]
