# Generated by Django 5.2 on 2025-06-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип кузова')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типы кузова',
            },
        ),
        migrations.CreateModel(
            name='CarPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название парка')),
                ('address', models.CharField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Автопарк',
                'verbose_name_plural': 'Автопарки',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='vehicles.bodytype', verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобиля',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Гос. номер')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость автомобиля')),
                ('daily_rental_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Суточная стоимость проката')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для проката')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Изображение автомобиля')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.carmodel', verbose_name='Модель')),
                ('car_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.carpark', verbose_name='Автопарк')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
