# Generated by Django 5.2.4 on 2025-09-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='certificate',
            field=models.TextField(blank=True, null=True, verbose_name='Сертификат'),
        ),
    ]
