# Generated by Django 5.2.4 on 2025-10-26 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='certificate',
        ),
        migrations.CreateModel(
            name='CertificateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст детали')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_details', to='content.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Деталь сертификата',
                'verbose_name_plural': 'Детали сертификата',
                'ordering': ['order'],
            },
        ),
    ]
