# Generated by Django 5.2.4 on 2025-10-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_companyinfo_certificate_certificatedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания сертификата'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи сертификата'),
        ),
    ]
