# Generated by Django 5.2.4 on 2025-11-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_certificatedetail_detail_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Slider', max_length=100, verbose_name='Название слайдера')),
                ('autoplay', models.BooleanField(default=True, verbose_name='Автоматическая прокрутка')),
                ('autoplay_speed', models.PositiveIntegerField(default=3000, verbose_name='Скорость автоматической прокрутки (в мс)')),
                ('arrows', models.BooleanField(default=True, verbose_name='Показывать стрелки')),
                ('dots', models.BooleanField(default=True, verbose_name='Показывать точки')),
            ],
            options={
                'verbose_name': 'Настройки слайдера',
                'verbose_name_plural': 'Настройки слайдеров',
            },
        ),
    ]
