# Generated by Django 5.2.4 on 2025-12-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Веб-сайт'),
        ),
    ]
