# Generated by Django 5.2.4 on 2025-12-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_contact_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
