# Generated by Django 5.2.4 on 2025-10-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_companyinfo_certificate_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatedetail',
            name='detail_type',
            field=models.CharField(choices=[('text', 'Текст'), ('inn', 'ИНН'), ('reg', 'Регистрационный номер')], default='text', max_length=10, verbose_name='Тип детали'),
        ),
    ]
